services:
  postgres: # host
    image: postgres:15
    container_name: postgres-server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: codetatva_poc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d codetatva"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - poc-network

  pgadmin:
    image: dpage/pgadmin4:9.0
    container_name: pgadmin
#    profiles:
#      - local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80" # http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - poc-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  poc-network:

#docker compose up -d