spring:
  application:
    name: poc-resilience4j
  datasource:
    url: jdbc:postgresql://localhost:5432/codetatva_poc
    username: root
    password: password123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    # Recommended: enable dialect explicitly if you're getting metadata issues
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        connection:
          isolation: 2  # 2 = TRANSACTION_READ_COMMITTED

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
